# Generated by Django 5.0.2 on 2024-02-26 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0003_alter_produits_libelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AL', 'Alimentaire'), ('Mb', 'Meuble'), ('SN', 'Sanitaire'), ('Vs', 'Vaisselle'), ('Vt', 'Vetement'), ('Jx', 'Jouets'), ('Lg', 'Linge de maison'), ('Bj', 'Bijoux'), ('Dc', 'Decor')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='produits',
            name='catégorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='magasin.categorie'),
        ),
    ]
