# Generated by Django 5.0.2 on 2024-02-26 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0004_categorie_produits_catégorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(choices=[('AL', 'Alimentaire'), ('Mb', 'Meuble'), ('SN', 'Sanitaire'), ('Vs', 'Vaisselle'), ('Vt', 'Vetement'), ('Jx', 'Jouets'), ('Lg', 'Linge de maison'), ('Bj', 'Bijoux'), ('Dc', 'Decor'), ('F', 'Frais'), ('El', 'Electroménager'), ('im', 'immobilier'), ('par', 'parapharmacie'), ('tp', 'tapis')], max_length=50),
        ),
        migrations.AddField(
            model_name='produits',
            name='Fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='magasin.fournisseur'),
        ),
    ]
